const cities = [
  "Dumti, India",
  "Arzamas, Russia",
  "Baku, Azerbaijan",
  "Surat, India",
  "Beatty, Nevada",
  "Mosul, Iraq",
  "Visby, Sweden",
  "Instanbul, Turkey",
  "Genoa, Italy",
  "Okato, New Zealand",
  "Nova Russas, Brazil",
  "Ceske Budejovice, Czechia",
  "Christchurch, New Zealand",
  "Castelo Branco, Portugal",
  "Curico, Chile",
  "Sokode, Togo",
  "Monkey Bay, Malawi",
  "Atalya, Turkey",
  "Ambanja, Madagascar",
  "Saint-Pierre, San-Pierre Et Miquelon",
  "Krasnodar, Russia",
  "Jose De San Martin, Argentina",
  "Derby, Australia",
  "Manaus, Brazil",
  "Pune, India",
  "Hasik, Oman",
  "Velingrad, Bulgaria",
  "Marrakesh, Morocco",
  "Orlando, Florida",
  "Charlotte, North Carolina",
  "Edmonton, Alberta",
  "Vladivostok, Russia",
  "Cochabamba, Bolivia",
  "Tacurong, Philippines"
];
