const cities = [
  "Accra, Ghana",
  "Algiers, Algeria",
  "Arles, France",
  "Buffalo, New York",
  "Cairo, Egypt",
  "Casablanca, Morocco",
  "Copenhagen, Denmark",
  "DeKalb, Illinois",
  "Dimtu, Ethiopia",
  "Divo, Côte d'Ivoire",
  "Eyjafjallajökull, Iceland",
  "Georgetown, Ascension Island",
  "Heard Island, Australia",
  "Possession Island, France",
  "Iturup, Japan/Russia",
  "Kabul, Afghanistan",
  "Kupang, Indonesia",
  "Lahore, Pakistan",
  "Lima, Peru",
  "Maputo, Mozambique",
  "Montreal, Quebec",
  "Moscow, Russia",
  "Nazaré, Portugal",
  "Nome, Alaska",
  "Cairns, Queensland, Australia",
  "Quito, Ecuador",
  "Seoul, South Korea",
  "Tampa, Florida",
  "Tashkent, Uzbekistan",
  "Tierra del Fuego",
  "Tijuana, Mexico",
  "Toad Suck, Arkansas",
  "Upper Hutt, New Zealand",
  "Wichita, Kansas",
  "Yellowknife, Northwest Territories",
  "Ankara, Turkey",
  "Babylon, Iraq",
  "Malé, Maldives",
  "Tallinn, Estonia",
  "Thane, India",
  "Arzamas, Russia",
  "Baku, Azerbaijan",
  "Surat, India",
  "Beatty, Nevada",
  "Mosul, Iraq",
  "Visby, Sweden",
  "Istanbul, Turkey",
  "Genoa, Italy",
  "Okato, New Zealand",
  "Nova Russas, Brazil",
  "České Budějovice, Czechia",
  "Christchurch, New Zealand",
  "Castelo Branco, Portugal",
  "Curicó, Chile",
  "Sokodé, Togo",
  "Monkey Bay, Malawi",
  "Antalya, Turkey",
  "Ambanja, Madagascar",
  "Qingdao, China",
  "Saint-Pierre",
  "Salvador, Brazil",
  "José de San Martín, Argentina",
  "Derby, Australia",
  "Manaus, Brazil",
  "Pune, India",
  "Hasik, Oman",
  "Velingrad, Bulgaria",
  "Marrakesh, Morocco",
  "Orlando, Florida",
  "Charlotte, North Carolina",
  "Edmonton, Alberta",
  "Vladivostok, Russia",
  "Cochabamba, Bolivia",
  "Tacurong, Philippine"
];
