const cities = 
[
  "ABOUTSLEDGES      Ambanja, Madagascar",
  "AL, US",
  "ALGIERS, ALGERIA",
  "ANTALYA, TURKEY",
  "ARZAMAS, RUSSIA",
  "ATKINSON      PROSPECT      Rochester, NY",
  "AZ, US",
  "Aberdeen, WA",
  "Accra, Lima",
  "Algiers, Algeria",
  "Algiers, Algeria    Tampa Bay",
  "Ambanja, Madagascar",
  "Astoria, OR",
  "Atlantic City, NJ",
  "Ayacucho, Peru",
  "BAKU, AZERBAIJAN",
  "BEATTY, NEVADA",
  "Bay Area, Los Angeles",
  "Buffalo, New York",
  "CA, US",
  "CASTELO BRANCO, PORTUGAL",
  "CB, Patriots",
  "CB, Seahawks",
  "CHRISTCHURCH, NEW ZEALAND",
  "CO, US",
  "COLFAX      ONEIDA      Denver, CO",
  "COPENHAGEN, DENMARK",
  "CRACOVIA      San Juan, Puerto Rico",
  "Cairns, Queensland",
  "California, Oregon",
  "Canada    Queensland, Australia    Divo",
  "Canada, Europe",
  "Charlotte, North Carolina",
  "Chicago Bears, Linebacker",
  "Cochabamba, Bolivia",
  "Cracovia, McGuckian",
  "Crescent City, CA",
  "DAR  \u00a0ES SALAAM, TANZANIA",
  "DE LA POSSESSION, FRANCE",
  "DE, Giants",
  "DEAMBULATORY      Nova Russas, Brazil",
  "DEKALB, IL",
  "DeKalb, Illinois",
  "Derby, Western Australia",
  "ECTYPOGRAPHY      Krasnodar, Russia",
  "EPANOSTROPHE      Derby, Australia",
  "EXSANGUINOUS      Manaus, Brazil",
  "Edmonton, Alberta",
  "Edmonton, Canada",
  "FL, USA",
  "Florida    Wichita, Kansas    Tierra",
  "GEORGETOWN, ASCENSION ISLAND",
  "GREENFOREST      MOCKINGBIRD      Wilmington, NC",
  "Genoa, Italy",
  "Grants Pass, OR",
  "HAPAXANTHOUS      Baku, Azerbaijan",
  "Hasik, Oman",
  "INCLINOMETER      Surat, India",
  "ISTANBUL, TURKEY",
  "Ilwaco, WA",
  "Ilwaco, Washington",
  "Ivory Coast    Copenhagen, Denmark    Buffalo",
  "Ivory Coast, DIVO",
  "JUANDEZOYAS      MAESEFARFAN      Seville, ES",
  "KALYPSO      ANNALUE      Auburn, AL",
  "KUPANG, INDONESIA",
  "KY, US",
  "Krasnodar, Russia",
  "LACHRYMIFORM      Christchurch, New Zealand",
  "LAEVODUCTION      Castelo Branco, Portugal",
  "LAHORE, PAKISTAN",
  "LAMPADEPHORE      Pune, India",
  "LB, Cowboys",
  "LEIPZIGER      OSCHATZER      Dresden, Germany",
  "LIGNIPERDOUS      Hasik, Oman",
  "LIMA, PERU",
  "LOWTHER      GOSCHEN      Dover, UK",
  "La, Ho",
  "Lincoln, Nebraska",
  "MACHAIRODONT      Velingrad, Bulgaria",
  "MALE, MALDIVES",
  "MARINAGLEN      DELTAQUEEN      Sacramento, CA",
  "MCGUCKIAN      MCKENDREE      Annapolis, MD",
  "MCKEMY      APOLLO      Tempe, AZ",
  "MD, US",
  "MLB, Bears",
  "MONKEY BAY, MALAWI",
  "MONTREAL, CANADA",
  "MOSCOW, RUSSIA",
  "MOSUL, IRAQ",
  "Macon, Georgia",
  "Main St, Los Angeles",
  "Manaus, Amazonas",
  "Marrakesh, Morocco",
  "NARRISCHKEIT      Marrakesh, Morocco",
  "NC, USA",
  "NEBRASKA      WESTWOOD      Toledo, OH",
  "NEBULOPHOBIA      Beaty, Nevada",
  "NEWZEALAND    Lower Hutt, New Zealand",
  "NIMONS      BRUTON      Orlando, FL",
  "NM, USA",
  "NOW, HERE",
  "NY, US",
  "New York Giants, Defensive",
  "Newport, OR",
  "OCHROLEUCOUS      Mosul, Iraq",
  "ODORIVECTORS      Orlando, Florida",
  "OH, US",
  "ON, CA",
  "OXFORD      BITTEL      Owensboro, KY",
  "Oxford, Nebraska",
  "Pierre, France",
  "Pittsburgh Steelers, Wide",
  "Pune, Maharashtra",
  "QUEENSLAND, AUSTRALIA",
  "QUITO, ECUADOR",
  "RECEPTACULAR      Visby, Sweden",
  "RISORGIMENTO      Istanbul, Turkey",
  "Re, Pa",
  "SA, Australia",
  "SAPONIFIABLE      Charlotte, North Carolina",
  "SEOUL, SOUTH KOREA",
  "SERPENTICIDE      Edmonton, Canada",
  "SK, CA",
  "SNALLYGASTER      Vladivostok, Russia",
  "SOKODE, TOGO",
  "SPIELBERG MOVIE, OR",
  "SUMMIT      CAHOON      Roswell, NM",
  "Saint Helena, Ascension",
  "Seville, Spain",
  "TALLINN, ESTONIA",
  "TE, Chiefs",
  "TERAMORPHOUS      Cochabamba, Bolivia",
  "TIJUANA, MEXICO",
  "TOAD SUCK, ARKANSAS",
  "TX, US",
  "Tacurong, Philippines",
  "Tampa Bay, Florida",
  "Toronto, Canada",
  "Toronto, Toledo",
  "UMAGE, THE SEAH",
  "VISBY, SWEDEN",
  "Velingrad, Bulgaria",
  "Vladivostok, Russia",
  "WASCANA      DEWDNEY      Regina, SK",
  "WICHITA, KANSAS",
  "WINTERBOURNE      Tacurong, Philippines",
  "WR, Steelers",
  "Warsaw, PL",
  "Wellington, New Zealand",
  "Wharf, Australia",
  "Wichita, Denver",
  "XXXYYYY, XXXZZZZ",
  "YELLOWKNIFE, CANADA"
];
